### ISSUE TITLE
Possible issue with the runtime cache

### ISSUE THREAD

**Issue by Matthew-Wise** [Bjornmamman/Our.Umbraco.AutoImageOptimze#1]
https://github.com/Bjornmamman/Our.Umbraco.AutoImageOptimze/blob/master/Our.Umbraco.AutoImageOptimze/ImageProccessingComponent.cs#L47

I can see you have a runtime cache that is using the request path and query as the key. I think it should cache using the AcceptTypes as well.

Otherwise you will serve webp images to browsers that don't support it.

Matt

**Comment by madsoulswe** [comment]
That is true! And I thought of another issue with the caching.
